# Generated by Django 6.0.6 on 2026-07-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_amenity_property_amenities_propertydocument_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertydocument',
            old_name='file',
            new_name='document',
        ),
        migrations.AlterField(
            model_name='property',
            name='google_map',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('Sold', 'Sold')], default='For Sale', max_length=30),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
