# Generated by Django 6.0.6 on 2026-07-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_owner_property_slug_property_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Property',
            name='google_map',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
