# Generated by Django 6.0.6 on 2026-07-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_file_propertydocument_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.RemoveField(
            model_name='propertydocument',
            name='title',
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/'),
        ),
    ]
