# Generated by Django 6.0.6 on 2026-08-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='boundary_points',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
