# Generated by Django 6.0.6 on 2026-08-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_boundary_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='survey_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
