# Generated by Django 5.1.1 on 2026-07-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyRentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('survey_no', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('village_name', models.CharField(max_length=255)),
                ('district_name', models.CharField(max_length=255)),
                ('taluka_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=255)),
                ('taluka', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalCourtService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('survey_no', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=255)),
                ('taluka', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('problem_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('survey_no', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('taluka', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NAService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('survey_no', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=255)),
                ('taluka', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('na_papers', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('survey_no', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('village_name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('taluka', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('Land', 'Land'), ('Home', 'Home'), ('Shop', 'Shop'), ('Plot', 'Plot')], max_length=50)),
                ('buy_rent', models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
