# Generated by Django 5.1.1 on 2026-07-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellservice',
            name='building_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
