# Generated by Django 5.1.1 on 2026-07-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_sellservice_building_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellservice',
            name='survey_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
