# Generated by Django 5.1.1 on 2026-07-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_sellservice_survey_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAlertService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('property_type', models.CharField(choices=[('Land', 'Land'), ('Home', 'Home'), ('Shop', 'Shop'), ('Plot', 'Plot')], max_length=50)),
                ('buy_rent', models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('taluka', models.CharField(max_length=255)),
                ('budget_range', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
