# Generated by Django 6.0.6 on 2026-07-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_propertyalertservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyalertservice',
            name='building_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='propertyalertservice',
            name='survey_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
