# Generated by Django 6.0.6 on 2026-07-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_propertyalertservice_building_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellservice',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
