# Generated by Django 6.0.6 on 2026-07-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_sellservice_area_sellservice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrentservice',
            name='building_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='legalcourtservice',
            name='building_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='measurementservice',
            name='building_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='naservice',
            name='building_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='buyrentservice',
            name='survey_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='legalcourtservice',
            name='survey_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='measurementservice',
            name='survey_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='naservice',
            name='survey_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
