# Generated by Django 6.0.6 on 2026-07-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_buyrentservice_building_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naservice',
            name='building_name',
        ),
        migrations.AlterField(
            model_name='naservice',
            name='survey_no',
            field=models.CharField(max_length=100),
        ),
    ]
