# Generated by Django 6.0.6 on 2026-07-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_naservice_building_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyalertservice',
            name='budget_range',
        ),
        migrations.RemoveField(
            model_name='propertyalertservice',
            name='buy_rent',
        ),
    ]
