# Generated by Django 6.0.6 on 2026-07-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_propertyalertservice_budget_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyrentservice',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
