# Generated by Django 6.0.6 on 2026-07-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_buyrentservice_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentLandService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('survey_no', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=255)),
                ('taluka', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('matter_details', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandDocumentationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('survey_no', models.CharField(blank=True, default='', max_length=100)),
                ('building_name', models.CharField(blank=True, default='', max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('taluka', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='buyrentservice',
            name='buy_rent',
            field=models.CharField(blank=True, choices=[('Buy', 'Buy'), ('Rent', 'Rent')], default='', max_length=10),
        ),
    ]
