# Generated by Django 6.0.6 on 2026-08-01 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_is_approved'),
        ('services', '0011_governmentlandservice_landdocumentationservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellservice',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_inquiries', to='properties.property'),
        ),
    ]
