# Generated by Django 6.0.6 on 2026-08-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_sellservice_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandFinanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('survey_no', models.CharField(blank=True, default='', max_length=100)),
                ('building_name', models.CharField(blank=True, default='', max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('taluka', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('land_area', models.IntegerField(default=0)),
                ('loan_amount_required', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purpose', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
