# Generated by Django 6.0.6 on 2026-08-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_survey_no'),
        ('services', '0013_landfinanceservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrentservice',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_rent_inquiries', to='properties.property'),
        ),
    ]
