# Generated by Django 6.0.6 on 2026-08-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_landdocumentationservice_result_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentlandservice',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='government_land_documents/'),
        ),
        migrations.AddField(
            model_name='landfinanceservice',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='land_finance_documents/'),
        ),
        migrations.AddField(
            model_name='legalcourtservice',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='legal_court_documents/'),
        ),
        migrations.AddField(
            model_name='measurementservice',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='measurement_documents/'),
        ),
        migrations.AddField(
            model_name='naservice',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='na_service_documents/'),
        ),
        migrations.AddField(
            model_name='propertyalertservice',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='property_alert_documents/'),
        ),
    ]
