// Languages Google Translate's website widget supports.
// code === "en" is treated as "restore original text".
export const LANGUAGES = [
    { code: "en", name: "English" },
    { code: "hi", name: "Hindi", native: "हिन्दी" },
    { code: "gu", name: "Gujarati", native: "ગુજરાતી" },
    { code: "mr", name: "Marathi", native: "मराठी" },
    { code: "bn", name: "Bengali", native: "বাংলা" },
    { code: "ta", name: "Tamil", native: "தமிழ்" },
    { code: "te", name: "Telugu", native: "తెలుగు" },
    { code: "kn", name: "Kannada", native: "ಕನ್ನಡ" },
    { code: "ml", name: "Malayalam", native: "മലയാളം" },
    { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ" },
    { code: "ur", name: "Urdu", native: "اردو" },
    { code: "or", name: "Odia", native: "ଓଡ଼ିଆ" },
    { code: "as", name: "Assamese", native: "অসমীয়া" },
    { code: "sa", name: "Sanskrit", native: "संस्कृतम्" },
    { code: "sd", name: "Sindhi" },
    { code: "ne", name: "Nepali" },
    { code: "si", name: "Sinhala" },
    { code: "my", name: "Burmese" },
    { code: "zh-CN", name: "Chinese (Simplified)" },
    { code: "zh-TW", name: "Chinese (Traditional)" },
    { code: "ja", name: "Japanese" },
    { code: "ko", name: "Korean" },
    { code: "th", name: "Thai" },
    { code: "vi", name: "Vietnamese" },
    { code: "id", name: "Indonesian" },
    { code: "ms", name: "Malay" },
    { code: "tl", name: "Filipino" },
    { code: "fr", name: "French" },
    { code: "es", name: "Spanish" },
    { code: "pt", name: "Portuguese" },
    { code: "de", name: "German" },
    { code: "it", name: "Italian" },
    { code: "nl", name: "Dutch" },
    { code: "ru", name: "Russian" },
    { code: "pl", name: "Polish" },
    { code: "uk", name: "Ukrainian" },
    { code: "ro", name: "Romanian" },
    { code: "el", name: "Greek" },
    { code: "tr", name: "Turkish" },
    { code: "he", name: "Hebrew" },
    { code: "ar", name: "Arabic" },
    { code: "fa", name: "Persian" },
    { code: "sw", name: "Swahili" },
    { code: "af", name: "Afrikaans" },
    { code: "am", name: "Amharic" },
];
