# Generated by Django 5.1.1 on 2026-07-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_alter_savedproperty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedproperty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
